server:
  PROJECT_NAME: "Core Api"
  SERVICE_NAME: "core_api"
  APP_ENV: "dev"
  API_VER: "v1"
  APP_DEBUG: true
  APP_PROXY: false
  APP_PROXY_HOST: "http://192.168.1.207:8888"
  HTTP_PORT: 8080
  GRPC_PORT: 8080
  TIMEOUT: 15
  APP_SECRET: "02C95ywn67189E2PzJSIknopADHKZ2PzQhT2B2DDA1o54E2oBTOYGqda8WWc9BFFGpaMh9C5"
  JWT_TOKEN_EXPIRE_TIME: 8760
  APP_VERSION: 1.0.0
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  MAX_CONN_IDLE: 5
  MAX_CONN_AGE: 5

swagger:
  SWAGGER_BASIC_AUTH_USERNAME:
  SWAGGER_BASIC_AUTH_PASSWORD:

cloud:
  GCP_PROJECT_IDENTIFIER:
  AWS_PROJECT_IDENTIFIER:
  GCP_SERVICE_ACCOUNT:

http:
  PORT: 8080
  PPROF_PORT: 8080
  TIMEOUT: 15
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  COOKIE_LIFE_TIME: 44640
  SESSION_COOKIE_NAME: "session_token"
  SSL_CERT_PATH: ""
  SSL_CERT_KEY: ""

logger:
  DISABLE_CALLER: false
  DISABLE_STACKTRACE: false
  ENCODING: json
  LEVEL: info

postgresql-prod:
  HOST: "128.140.65.228"
  PORT: 5432
  USER: "students"
  PASS: "23@4!3Aa2bh"
  DEFAULT_DB: "dev"
  MAX_CONN: 10
  DRIVER: "pgx"

postgresql:
  HOST: "127.0.0.1"
  PORT: 5432
  USER: "postgres"
  PASS: "123456"
  DEFAULT_DB: "dev"
  MAX_CONN: 10
  DRIVER: "pgx"

mongodb:
  HOST: "docdb.xmg8e.mongodb.net"
  PORT:
  USER: "ivanbarayev"
  PASS: "29hEPWkPEkTF8KWY"
  DEFAULT_DB: "DocDB"
  MONGO_DB_ATLAS: "mongodb+srv://{USER_NAME}:{USER_PASS}@{DB_HOST}/{DEFAULT_DB}?retryWrites=true&w=majority"

redis:
  HOST: "128.140.65.228"
  PORT: 6379
  USER: "default"
  PASS: "KaFUZUqnYWDl1nxku0QjPM1"
  DEFAULT_DB: 0
  MIN_IDLE_CONN: 5
  POOL_SIZE: 5
  POOL_TIMEOUT: 20

