--region users
CREATE TABLE users
(
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INT8 NOT NULL,
    email varchar(100) NOT NULL,
    phone varchar(13) DEFAULT NULL,
    address varchar(255) DEFAULT NULL,
    user_name varchar(50) DEFAULT NULL,
    password varchar(255) DEFAULT NULL,
    has_gdpr boolean DEFAULT false,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX ON users USING btree (user_name);
CREATE INDEX ON users USING btree (phone);
CREATE INDEX ON users USING btree (email,password);
--endregion