name: Go package

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    runs-on: runner-stage
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Build
        run: make start
